exclude:
- /dist/.*
- /projects/build-spring-framework/.*
- /projects/org.springframework.aop/lib/.*
- /projects/org.springframework.aop/target/.*
- /projects/org.springframework.asm/.*
- /projects/org.springframework.beans/lib/.*
- /projects/org.springframework.beans/target/.*
- /projects/org.springframework.context/lib/.*
- /projects/org.springframework.context/target/.*
- /projects/org.springframework.context.support/lib/.*
- /projects/org.springframework.context.support/target/.*
- /projects/org.springframework.core/lib/.*
- /projects/org.springframework.core/target/.*
- /projects/org.springframework.expression/lib/.*
- /projects/org.springframework.expression/target/.*
- /projects/org.springframework.instrument/target/.*
- /projects/org.springframework.instrument.tomcat/lib/.*
- /projects/org.springframework.instrument.tomcat/target/.*
- /projects/org.springframework.integration-tests/lib/.*
- /projects/org.springframework.integration-tests/target/.*
- /projects/org.springframework.jdbc/lib/.*
- /projects/org.springframework.jdbc/target/.*
- /projects/org.springframework.jms/lib/.*
- /projects/org.springframework.jms/target/.*
- /projects/org.springframework.orm/lib/.*
- /projects/org.springframework.orm/target/.*
- /projects/org.springframework.oxm/target/.*
- /projects/org.springframework.spring-library/.*
- /projects/org.springframework.spring-parent/.*
- /projects/org.springframework.test/lib/.*
- /projects/org.springframework.test/target/.*
- /projects/org.springframework.transaction/lib/.*
- /projects/org.springframework.transaction/target/.*
- /projects/org.springframework.web/lib/.*
- /projects/org.springframework.web/target/.*
- /projects/org.springframework.web.portlet/lib/.*
- /projects/org.springframework.web.portlet/target/.*
- /projects/org.springframework.web.servlet/lib/.*
- /projects/org.springframework.web.servlet/target/.*
- /projects/org.springframework.web.struts/lib/.*
- /projects/org.springframework.web.struts/target/.*
- /projects/spring-build/.*
- /projects/spring-framework-reference/.*
